-- Migration 003: real accounts with ASP.NET Core Identity, roles, and
-- temporary guest accounts.
--
-- Replaces the hand-written app_user from 001 with the tables Identity
-- expects, renamed to snake_case to match AccountsContext.
--
-- The accounts from 001 were placeholders for testing, so they are erased
-- rather than carried over. Erasing them erases their saved books too.
--
-- Run once on the server, only together with the API code that uses it:
--
--   docker compose exec -T db sh -c \
--     'psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"' \
--     < db/migrations/003_identity.sql

BEGIN;

-- 1. Erase the placeholder data. Deleting books cascades to their answers,
--    selections, and uploaded covers.
DELETE FROM book_session;

-- 2. Remove the old accounts table. CASCADE also drops book_session's
--    foreign key to it, which is added back in step 5.
DROP TABLE app_user CASCADE;

-- 3. Identity's tables.

-- Accounts. user_name always equals the email address, except for guests,
-- who get guest-<id> and an address at guest.invalid that can never
-- receive mail and can never be registered.
CREATE TABLE app_user (
    id                      uuid          PRIMARY KEY,
    user_name               varchar(256),
    normalized_user_name    varchar(256),
    email                   varchar(256),
    normalized_email        varchar(256),
    email_confirmed         boolean       NOT NULL DEFAULT false,
    password_hash           text,
    security_stamp          text,
    concurrency_stamp       text,
    phone_number            text,
    phone_number_confirmed  boolean       NOT NULL DEFAULT false,
    two_factor_enabled      boolean       NOT NULL DEFAULT false,
    lockout_end             timestamptz,
    lockout_enabled         boolean       NOT NULL DEFAULT true,
    access_failed_count     int           NOT NULL DEFAULT 0,
    created_at              timestamptz   NOT NULL DEFAULT now(),

    -- Set only on guest accounts: when the cleanup job deletes it.
    guest_expires_at        timestamptz,

    -- Set on a new account whose owner chose to keep their guest books.
    -- The books move over when the email is confirmed. If the guest
    -- account expires first, this clears itself.
    pending_guest_id        uuid          REFERENCES app_user(id) ON DELETE SET NULL
);

-- One account per email, enforced by the database as well as the API.
CREATE UNIQUE INDEX app_user_normalized_user_name_idx ON app_user (normalized_user_name);
CREATE UNIQUE INDEX app_user_normalized_email_idx     ON app_user (normalized_email);

-- The cleanup job looks for expired guests every hour.
CREATE INDEX app_user_guest_expires_idx ON app_user (guest_expires_at)
    WHERE guest_expires_at IS NOT NULL;

CREATE TABLE app_role (
    id                 uuid         PRIMARY KEY,
    name               varchar(256),
    normalized_name    varchar(256) UNIQUE,
    concurrency_stamp  text
);

-- Which accounts have which roles.
CREATE TABLE app_user_role (
    user_id  uuid  NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    role_id  uuid  NOT NULL REFERENCES app_role(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Identity requires these next four tables to exist. VeggieBook2 does not
-- use them yet (no outside sign-in providers, no stored tokens).
CREATE TABLE app_user_claim (
    id           int   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      uuid  NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    claim_type   text,
    claim_value  text
);

CREATE TABLE app_role_claim (
    id           int   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id      uuid  NOT NULL REFERENCES app_role(id) ON DELETE CASCADE,
    claim_type   text,
    claim_value  text
);

CREATE TABLE app_user_login (
    login_provider         text  NOT NULL,
    provider_key           text  NOT NULL,
    provider_display_name  text,
    user_id                uuid  NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    PRIMARY KEY (login_provider, provider_key)
);

CREATE TABLE app_user_token (
    user_id         uuid  NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    login_provider  text  NOT NULL,
    name            text  NOT NULL,
    value           text,
    PRIMARY KEY (user_id, login_provider, name)
);

-- 4. The three roles.
--    Guest: temporary account, deleted on sign out or after 24 hours.
--    User:  every real account.
--    Admin: given only by hand on the server, together with User.
INSERT INTO app_role (id, name, normalized_name, concurrency_stamp) VALUES
    (gen_random_uuid(), 'Guest', 'GUEST', gen_random_uuid()::text),
    (gen_random_uuid(), 'User',  'USER',  gen_random_uuid()::text),
    (gen_random_uuid(), 'Admin', 'ADMIN', gen_random_uuid()::text);

-- 5. Saved books belong to the new accounts table.
ALTER TABLE book_session
    ADD CONSTRAINT book_session_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

COMMIT;